#Postgresql
#development:
#  adapter: postgresql
#  encoding: unicode
#  database: pmanager_development
#  pool: 5
#  username: postgres
#  password: master1
#  host: localhost
#  port: 5432
development:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 #database: siematec
 database: sgs_development
 pool: 5
 username: root
 password: master1
 host: localhost

test:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: siematec
 #database: sgs_development
 pool: 5
 username: root
 password: master1
 host: localhost

production:
 adapter: mysql2
 encoding: utf8
 reconnect: false
 database: siematec
 #database: sgs_development
 pool: 5
 username: root
 password: master1
 host: localhost
