require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CategoriaClientesController do

  def mock_categoria_cliente(stubs={})
    @mock_categoria_cliente ||= mock_model(CategoriaCliente, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all categoria_clientes as @categoria_clientes" do
      CategoriaCliente.stub(:all) { [mock_categoria_cliente] }
      get :index
      assigns(:categoria_clientes).should eq([mock_categoria_cliente])
    end
  end

  describe "GET show" do
    it "assigns the requested categoria_cliente as @categoria_cliente" do
      CategoriaCliente.stub(:find).with("37") { mock_categoria_cliente }
      get :show, :id => "37"
      assigns(:categoria_cliente).should be(mock_categoria_cliente)
    end
  end

  describe "GET new" do
    it "assigns a new categoria_cliente as @categoria_cliente" do
      CategoriaCliente.stub(:new) { mock_categoria_cliente }
      get :new
      assigns(:categoria_cliente).should be(mock_categoria_cliente)
    end
  end

  describe "GET edit" do
    it "assigns the requested categoria_cliente as @categoria_cliente" do
      CategoriaCliente.stub(:find).with("37") { mock_categoria_cliente }
      get :edit, :id => "37"
      assigns(:categoria_cliente).should be(mock_categoria_cliente)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created categoria_cliente as @categoria_cliente" do
        CategoriaCliente.stub(:new).with({'these' => 'params'}) { mock_categoria_cliente(:save => true) }
        post :create, :categoria_cliente => {'these' => 'params'}
        assigns(:categoria_cliente).should be(mock_categoria_cliente)
      end

      it "redirects to the created categoria_cliente" do
        CategoriaCliente.stub(:new) { mock_categoria_cliente(:save => true) }
        post :create, :categoria_cliente => {}
        response.should redirect_to(categoria_cliente_url(mock_categoria_cliente))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved categoria_cliente as @categoria_cliente" do
        CategoriaCliente.stub(:new).with({'these' => 'params'}) { mock_categoria_cliente(:save => false) }
        post :create, :categoria_cliente => {'these' => 'params'}
        assigns(:categoria_cliente).should be(mock_categoria_cliente)
      end

      it "re-renders the 'new' template" do
        CategoriaCliente.stub(:new) { mock_categoria_cliente(:save => false) }
        post :create, :categoria_cliente => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested categoria_cliente" do
        CategoriaCliente.stub(:find).with("37") { mock_categoria_cliente }
        mock_categoria_cliente.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :categoria_cliente => {'these' => 'params'}
      end

      it "assigns the requested categoria_cliente as @categoria_cliente" do
        CategoriaCliente.stub(:find) { mock_categoria_cliente(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:categoria_cliente).should be(mock_categoria_cliente)
      end

      it "redirects to the categoria_cliente" do
        CategoriaCliente.stub(:find) { mock_categoria_cliente(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(categoria_cliente_url(mock_categoria_cliente))
      end
    end

    describe "with invalid params" do
      it "assigns the categoria_cliente as @categoria_cliente" do
        CategoriaCliente.stub(:find) { mock_categoria_cliente(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:categoria_cliente).should be(mock_categoria_cliente)
      end

      it "re-renders the 'edit' template" do
        CategoriaCliente.stub(:find) { mock_categoria_cliente(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested categoria_cliente" do
      CategoriaCliente.stub(:find).with("37") { mock_categoria_cliente }
      mock_categoria_cliente.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the categoria_clientes list" do
      CategoriaCliente.stub(:find) { mock_categoria_cliente }
      delete :destroy, :id => "1"
      response.should redirect_to(categoria_clientes_url)
    end
  end

end
