require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CheckListItensController do

  def mock_check_list_item(stubs={})
    @mock_check_list_item ||= mock_model(CheckListItem, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all check_list_itens as @check_list_itens" do
      CheckListItem.stub(:all) { [mock_check_list_item] }
      get :index
      assigns(:check_list_itens).should eq([mock_check_list_item])
    end
  end

  describe "GET show" do
    it "assigns the requested check_list_item as @check_list_item" do
      CheckListItem.stub(:find).with("37") { mock_check_list_item }
      get :show, :id => "37"
      assigns(:check_list_item).should be(mock_check_list_item)
    end
  end

  describe "GET new" do
    it "assigns a new check_list_item as @check_list_item" do
      CheckListItem.stub(:new) { mock_check_list_item }
      get :new
      assigns(:check_list_item).should be(mock_check_list_item)
    end
  end

  describe "GET edit" do
    it "assigns the requested check_list_item as @check_list_item" do
      CheckListItem.stub(:find).with("37") { mock_check_list_item }
      get :edit, :id => "37"
      assigns(:check_list_item).should be(mock_check_list_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created check_list_item as @check_list_item" do
        CheckListItem.stub(:new).with({'these' => 'params'}) { mock_check_list_item(:save => true) }
        post :create, :check_list_item => {'these' => 'params'}
        assigns(:check_list_item).should be(mock_check_list_item)
      end

      it "redirects to the created check_list_item" do
        CheckListItem.stub(:new) { mock_check_list_item(:save => true) }
        post :create, :check_list_item => {}
        response.should redirect_to(check_list_item_url(mock_check_list_item))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved check_list_item as @check_list_item" do
        CheckListItem.stub(:new).with({'these' => 'params'}) { mock_check_list_item(:save => false) }
        post :create, :check_list_item => {'these' => 'params'}
        assigns(:check_list_item).should be(mock_check_list_item)
      end

      it "re-renders the 'new' template" do
        CheckListItem.stub(:new) { mock_check_list_item(:save => false) }
        post :create, :check_list_item => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested check_list_item" do
        CheckListItem.stub(:find).with("37") { mock_check_list_item }
        mock_check_list_item.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :check_list_item => {'these' => 'params'}
      end

      it "assigns the requested check_list_item as @check_list_item" do
        CheckListItem.stub(:find) { mock_check_list_item(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:check_list_item).should be(mock_check_list_item)
      end

      it "redirects to the check_list_item" do
        CheckListItem.stub(:find) { mock_check_list_item(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(check_list_item_url(mock_check_list_item))
      end
    end

    describe "with invalid params" do
      it "assigns the check_list_item as @check_list_item" do
        CheckListItem.stub(:find) { mock_check_list_item(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:check_list_item).should be(mock_check_list_item)
      end

      it "re-renders the 'edit' template" do
        CheckListItem.stub(:find) { mock_check_list_item(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested check_list_item" do
      CheckListItem.stub(:find).with("37") { mock_check_list_item }
      mock_check_list_item.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the check_list_itens list" do
      CheckListItem.stub(:find) { mock_check_list_item }
      delete :destroy, :id => "1"
      response.should redirect_to(check_list_itens_url)
    end
  end

end
