require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ClienteCheckListItensController do

  def mock_cliente_check_list(stubs={})
    @mock_cliente_check_list ||= mock_model(ClienteCheckListItem, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all cliente_check_list_itens as @cliente_check_list_itens" do
      ClienteCheckListItem.stub(:all) { [mock_cliente_check_list] }
      get :index
      assigns(:cliente_check_list_itens).should eq([mock_cliente_check_list])
    end
  end

  describe "GET show" do
    it "assigns the requested cliente_check_list_item as @cliente_check_list_item" do
      ClienteCheckListItem.stub(:find).with("37") { mock_cliente_check_list }
      get :show, :id => "37"
      assigns(:cliente_check_list_item).should be(mock_cliente_check_list)
    end
  end

  describe "GET new" do
    it "assigns a new cliente_check_list_item as @cliente_check_list_item" do
      ClienteCheckListItem.stub(:new) { mock_cliente_check_list }
      get :new
      assigns(:cliente_check_list_item).should be(mock_cliente_check_list)
    end
  end

  describe "GET edit" do
    it "assigns the requested cliente_check_list_item as @cliente_check_list_item" do
      ClienteCheckListItem.stub(:find).with("37") { mock_cliente_check_list }
      get :edit, :id => "37"
      assigns(:cliente_check_list_item).should be(mock_cliente_check_list)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created cliente_check_list_item as @cliente_check_list_item" do
        ClienteCheckListItem.stub(:new).with({'these' => 'params'}) { mock_cliente_check_list(:save => true) }
        post :create, :cliente_check_list_item => {'these' => 'params'}
        assigns(:cliente_check_list_item).should be(mock_cliente_check_list)
      end

      it "redirects to the created cliente_check_list_item" do
        ClienteCheckListItem.stub(:new) { mock_cliente_check_list(:save => true) }
        post :create, :cliente_check_list_item => {}
        response.should redirect_to(cliente_check_list_url(mock_cliente_check_list))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cliente_check_list_item as @cliente_check_list_item" do
        ClienteCheckListItem.stub(:new).with({'these' => 'params'}) { mock_cliente_check_list(:save => false) }
        post :create, :cliente_check_list_item => {'these' => 'params'}
        assigns(:cliente_check_list_item).should be(mock_cliente_check_list)
      end

      it "re-renders the 'new' template" do
        ClienteCheckListItem.stub(:new) { mock_cliente_check_list(:save => false) }
        post :create, :cliente_check_list_item => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cliente_check_list_item" do
        ClienteCheckListItem.stub(:find).with("37") { mock_cliente_check_list }
        mock_cliente_check_list.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :cliente_check_list_item => {'these' => 'params'}
      end

      it "assigns the requested cliente_check_list_item as @cliente_check_list_item" do
        ClienteCheckListItem.stub(:find) { mock_cliente_check_list(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:cliente_check_list_item).should be(mock_cliente_check_list)
      end

      it "redirects to the cliente_check_list_item" do
        ClienteCheckListItem.stub(:find) { mock_cliente_check_list(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(cliente_check_list_url(mock_cliente_check_list))
      end
    end

    describe "with invalid params" do
      it "assigns the cliente_check_list_item as @cliente_check_list_item" do
        ClienteCheckListItem.stub(:find) { mock_cliente_check_list(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:cliente_check_list_item).should be(mock_cliente_check_list)
      end

      it "re-renders the 'edit' template" do
        ClienteCheckListItem.stub(:find) { mock_cliente_check_list(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cliente_check_list_item" do
      ClienteCheckListItem.stub(:find).with("37") { mock_cliente_check_list }
      mock_cliente_check_list.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the cliente_check_list_itens list" do
      ClienteCheckListItem.stub(:find) { mock_cliente_check_list }
      delete :destroy, :id => "1"
      response.should redirect_to(cliente_check_lists_url)
    end
  end

end
