require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ClienteInfrasController do

  def mock_cliente_infra(stubs={})
    @mock_cliente_infra ||= mock_model(ClienteInfra, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all cliente_infras as @cliente_infras" do
      ClienteInfra.stub(:all) { [mock_cliente_infra] }
      get :index
      assigns(:cliente_infras).should eq([mock_cliente_infra])
    end
  end

  describe "GET show" do
    it "assigns the requested cliente_infra as @cliente_infra" do
      ClienteInfra.stub(:find).with("37") { mock_cliente_infra }
      get :show, :id => "37"
      assigns(:cliente_infra).should be(mock_cliente_infra)
    end
  end

  describe "GET new" do
    it "assigns a new cliente_infra as @cliente_infra" do
      ClienteInfra.stub(:new) { mock_cliente_infra }
      get :new
      assigns(:cliente_infra).should be(mock_cliente_infra)
    end
  end

  describe "GET edit" do
    it "assigns the requested cliente_infra as @cliente_infra" do
      ClienteInfra.stub(:find).with("37") { mock_cliente_infra }
      get :edit, :id => "37"
      assigns(:cliente_infra).should be(mock_cliente_infra)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created cliente_infra as @cliente_infra" do
        ClienteInfra.stub(:new).with({'these' => 'params'}) { mock_cliente_infra(:save => true) }
        post :create, :cliente_infra => {'these' => 'params'}
        assigns(:cliente_infra).should be(mock_cliente_infra)
      end

      it "redirects to the created cliente_infra" do
        ClienteInfra.stub(:new) { mock_cliente_infra(:save => true) }
        post :create, :cliente_infra => {}
        response.should redirect_to(cliente_infra_url(mock_cliente_infra))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cliente_infra as @cliente_infra" do
        ClienteInfra.stub(:new).with({'these' => 'params'}) { mock_cliente_infra(:save => false) }
        post :create, :cliente_infra => {'these' => 'params'}
        assigns(:cliente_infra).should be(mock_cliente_infra)
      end

      it "re-renders the 'new' template" do
        ClienteInfra.stub(:new) { mock_cliente_infra(:save => false) }
        post :create, :cliente_infra => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cliente_infra" do
        ClienteInfra.stub(:find).with("37") { mock_cliente_infra }
        mock_cliente_infra.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :cliente_infra => {'these' => 'params'}
      end

      it "assigns the requested cliente_infra as @cliente_infra" do
        ClienteInfra.stub(:find) { mock_cliente_infra(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:cliente_infra).should be(mock_cliente_infra)
      end

      it "redirects to the cliente_infra" do
        ClienteInfra.stub(:find) { mock_cliente_infra(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(cliente_infra_url(mock_cliente_infra))
      end
    end

    describe "with invalid params" do
      it "assigns the cliente_infra as @cliente_infra" do
        ClienteInfra.stub(:find) { mock_cliente_infra(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:cliente_infra).should be(mock_cliente_infra)
      end

      it "re-renders the 'edit' template" do
        ClienteInfra.stub(:find) { mock_cliente_infra(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cliente_infra" do
      ClienteInfra.stub(:find).with("37") { mock_cliente_infra }
      mock_cliente_infra.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the cliente_infras list" do
      ClienteInfra.stub(:find) { mock_cliente_infra }
      delete :destroy, :id => "1"
      response.should redirect_to(cliente_infras_url)
    end
  end

end
