require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe EtapasController do

  def mock_etapa(stubs={})
    @mock_etapa ||= mock_model(Etapa, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all etapas as @etapas" do
      Etapa.stub(:all) { [mock_etapa] }
      get :index
      assigns(:etapas).should eq([mock_etapa])
    end
  end

  describe "GET show" do
    it "assigns the requested etapa as @etapa" do
      Etapa.stub(:find).with("37") { mock_etapa }
      get :show, :id => "37"
      assigns(:etapa).should be(mock_etapa)
    end
  end

  describe "GET new" do
    it "assigns a new etapa as @etapa" do
      Etapa.stub(:new) { mock_etapa }
      get :new
      assigns(:etapa).should be(mock_etapa)
    end
  end

  describe "GET edit" do
    it "assigns the requested etapa as @etapa" do
      Etapa.stub(:find).with("37") { mock_etapa }
      get :edit, :id => "37"
      assigns(:etapa).should be(mock_etapa)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created etapa as @etapa" do
        Etapa.stub(:new).with({'these' => 'params'}) { mock_etapa(:save => true) }
        post :create, :etapa => {'these' => 'params'}
        assigns(:etapa).should be(mock_etapa)
      end

      it "redirects to the created etapa" do
        Etapa.stub(:new) { mock_etapa(:save => true) }
        post :create, :etapa => {}
        response.should redirect_to(etapa_url(mock_etapa))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved etapa as @etapa" do
        Etapa.stub(:new).with({'these' => 'params'}) { mock_etapa(:save => false) }
        post :create, :etapa => {'these' => 'params'}
        assigns(:etapa).should be(mock_etapa)
      end

      it "re-renders the 'new' template" do
        Etapa.stub(:new) { mock_etapa(:save => false) }
        post :create, :etapa => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested etapa" do
        Etapa.stub(:find).with("37") { mock_etapa }
        mock_etapa.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :etapa => {'these' => 'params'}
      end

      it "assigns the requested etapa as @etapa" do
        Etapa.stub(:find) { mock_etapa(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:etapa).should be(mock_etapa)
      end

      it "redirects to the etapa" do
        Etapa.stub(:find) { mock_etapa(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(etapa_url(mock_etapa))
      end
    end

    describe "with invalid params" do
      it "assigns the etapa as @etapa" do
        Etapa.stub(:find) { mock_etapa(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:etapa).should be(mock_etapa)
      end

      it "re-renders the 'edit' template" do
        Etapa.stub(:find) { mock_etapa(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested etapa" do
      Etapa.stub(:find).with("37") { mock_etapa }
      mock_etapa.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the etapas list" do
      Etapa.stub(:find) { mock_etapa }
      delete :destroy, :id => "1"
      response.should redirect_to(etapas_url)
    end
  end

end
