require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe StatusTempoEvolucoesController do

  def mock_status_tempo_evolucao(stubs={})
    @mock_status_tempo_evolucao ||= mock_model(StatusTempoEvolucao, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all status_tempo_evolucoes as @status_tempo_evolucoes" do
      StatusTempoEvolucao.stub(:all) { [mock_status_tempo_evolucao] }
      get :index
      assigns(:status_tempo_evolucoes).should eq([mock_status_tempo_evolucao])
    end
  end

  describe "GET show" do
    it "assigns the requested status_tempo_evolucao as @status_tempo_evolucao" do
      StatusTempoEvolucao.stub(:find).with("37") { mock_status_tempo_evolucao }
      get :show, :id => "37"
      assigns(:status_tempo_evolucao).should be(mock_status_tempo_evolucao)
    end
  end

  describe "GET new" do
    it "assigns a new status_tempo_evolucao as @status_tempo_evolucao" do
      StatusTempoEvolucao.stub(:new) { mock_status_tempo_evolucao }
      get :new
      assigns(:status_tempo_evolucao).should be(mock_status_tempo_evolucao)
    end
  end

  describe "GET edit" do
    it "assigns the requested status_tempo_evolucao as @status_tempo_evolucao" do
      StatusTempoEvolucao.stub(:find).with("37") { mock_status_tempo_evolucao }
      get :edit, :id => "37"
      assigns(:status_tempo_evolucao).should be(mock_status_tempo_evolucao)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created status_tempo_evolucao as @status_tempo_evolucao" do
        StatusTempoEvolucao.stub(:new).with({'these' => 'params'}) { mock_status_tempo_evolucao(:save => true) }
        post :create, :status_tempo_evolucao => {'these' => 'params'}
        assigns(:status_tempo_evolucao).should be(mock_status_tempo_evolucao)
      end

      it "redirects to the created status_tempo_evolucao" do
        StatusTempoEvolucao.stub(:new) { mock_status_tempo_evolucao(:save => true) }
        post :create, :status_tempo_evolucao => {}
        response.should redirect_to(status_tempo_evolucao_url(mock_status_tempo_evolucao))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved status_tempo_evolucao as @status_tempo_evolucao" do
        StatusTempoEvolucao.stub(:new).with({'these' => 'params'}) { mock_status_tempo_evolucao(:save => false) }
        post :create, :status_tempo_evolucao => {'these' => 'params'}
        assigns(:status_tempo_evolucao).should be(mock_status_tempo_evolucao)
      end

      it "re-renders the 'new' template" do
        StatusTempoEvolucao.stub(:new) { mock_status_tempo_evolucao(:save => false) }
        post :create, :status_tempo_evolucao => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested status_tempo_evolucao" do
        StatusTempoEvolucao.stub(:find).with("37") { mock_status_tempo_evolucao }
        mock_status_tempo_evolucao.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :status_tempo_evolucao => {'these' => 'params'}
      end

      it "assigns the requested status_tempo_evolucao as @status_tempo_evolucao" do
        StatusTempoEvolucao.stub(:find) { mock_status_tempo_evolucao(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:status_tempo_evolucao).should be(mock_status_tempo_evolucao)
      end

      it "redirects to the status_tempo_evolucao" do
        StatusTempoEvolucao.stub(:find) { mock_status_tempo_evolucao(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(status_tempo_evolucao_url(mock_status_tempo_evolucao))
      end
    end

    describe "with invalid params" do
      it "assigns the status_tempo_evolucao as @status_tempo_evolucao" do
        StatusTempoEvolucao.stub(:find) { mock_status_tempo_evolucao(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:status_tempo_evolucao).should be(mock_status_tempo_evolucao)
      end

      it "re-renders the 'edit' template" do
        StatusTempoEvolucao.stub(:find) { mock_status_tempo_evolucao(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested status_tempo_evolucao" do
      StatusTempoEvolucao.stub(:find).with("37") { mock_status_tempo_evolucao }
      mock_status_tempo_evolucao.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the status_tempo_evolucoes list" do
      StatusTempoEvolucao.stub(:find) { mock_status_tempo_evolucao }
      delete :destroy, :id => "1"
      response.should redirect_to(status_tempo_evolucoes_url)
    end
  end

end
